import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageType = 'so' | 'en' | 'am';

export const translations: Record<LanguageType, Record<string, string>> = {
  so: {
    app_name: "HOGAAN",
    dashboard: "Xogta Guud",
    pending_list: "Codsiyada Sugan",
    register: "Diiwaangali Arday",
    approved_students: "Ardayda La Aqbalay",
    manage_courses: "Maamul Koorsooyinka",
    ai_insights: "Falanqaynta AI",
    languages: "Luuqadaha",
    log_out: "Ka Bax",
    admin_user: "Maamulaha",
    main_admin: "Maamulaha Guud",
    welcome_system: "Goobta wax barashooyinka kala duwan",
    is_diiwaangali: "Is-diiwaangali",
    is_diiwaangali_desc: "Haddii aad tahay arday cusub oo raba inuu ku soo biiro dugsiga, halkan ka buuxi foomka diwaangalinta.",
    biloow_hadda: "Biloow Hadda",
    gali_koorsooyinka: "Gali Koorsooyinka",
    gali_koorsooyinka_desc: "Haddii aad tahay arday hore oo la aqbalay, halkan ka gal qaybta koorsooyinkaaga iyo casharadaada.",
    fura_koorsooyinka: "Fura Koorsooyinka",
    maamulka: "Maamulka",
    maamulka_desc: "Halkan waxaa loogu talagalay maamulka si ay u hubiyaan codsiyada iyo xogta guud ee ardayda.",
    gali_dashboard: "Gali Dashboard",
    all_rights_reserved: "Dhammaan xuquuqdu waa dhowran tahay.",
    student_auth: "Aqoonsiga Ardayga",
    student_auth_desc: "Gali Email-kaaga ama Telefoonkaaga si aad u gasho koorsooyinka.",
    email_phone: "Email / Telefoon",
    student_not_found: "Waan ka xunnahay, ardaygan laguma hayo nidaamka. Fadlan is-diwaangali.",
    student_pending: "Codsigaaga wali waa la sugayaa (Pending). Fadlan sug ilaa lagaa aqbalayo.",
    student_rejected: "Waan ka xunnahay, codsigaaga waa la diiday.",
    back_home: "Ku laabo bogga hore",
    go_back: "Ku Laabo Bogga Hore",
    new_student: "Arday Cusub",
    fill_details: "Ku soo biir dugsiga adoo buuxinaya faahfaahinta hoose.",
    full_name: "Magaca oo Buuxa",
    email: "Email",
    phone: "Telefoon",
    gender: "Jinsiga",
    male: "Lab",
    female: "Dhadig",
    birth_date: "Taariikhda dhalashada",
    address: "Ciwaanka",
    country: "Dalka",
    registration_type: "Qaabka Isdiwaangalinta",
    paid: "Lacag ah",
    free: "Free ah",
    amount: "Lacagta",
    currency: "Nooca Lacagta",
    add_student: "Ku dar Arday",
    submit_application: "Garaac halkan si aad u dirto codsigaaga",
    success_header: "Hambalyo!",
    success_desc: "Diiwaangalintaadu waxay u dhacday si guul leh. Codsigaaga waxaa dib u eegi doona maamulka.",
    active_approved_students: "Ardayda La Hubiyay ee Firfircoon",
    official_student_list: "Liiska rasmiga ah ee ardayda ka diiwaangashan nidaamka.",
    search_placeholder: "Raadi...",
    contact: "Xiriirka",
    info: "Xogta",
    address_country: "Booska / Ciwaanka",
    payment: "Lacag bixinta",
    date: "Taariikhda",
    cost: "Kharashka",
    pending_system_header: "Nidaamka Sugitaanka iyo Aqbalaada",
    pending_system_desc: "Hoos ka eeg codsiyada ardayda ku dhow in la hawl-geliyo.",
    pending_search_placeholder: "Raadi magac ama taleefan...",
    no_pending_applications: "Ma hayno codsiyo sugan oo la xaqiijinayo hadda.",
    approve: "Aqbal",
    reject: "Diid",
    course_management_header: "Maamulista Koorsooyinka",
    course_management_desc: "Kordhi ama wax ka badal koorsooyinka uu nidaamku bixiyo.",
    add_new_course: "Ku dar Koorso Cusub",
    course_title: "Magaca Koorsada",
    course_teacher: "Macalinka Koorsada",
    course_level: "Heerka Koorsada",
    course_desc: "Sifaynta Koorsada",
    icon: "Astaan / Icon",
    icon_color: "Midabka Astanta",
    thumbnail: "Sawir / Thumbnail (Optional)",
    current_courses: "Koorsooyinka Hadda Jira",
    no_courses_found: "Ma jiraan koorsooyin la helay.",
    my_courses: "Koorsooyinkayga",
    welcome_education: "Ku soo dhawaaw waxbarashadaada",
    teacher: "Macallin",
    level: "Heerka",
    desc: "Sifada",
    back: "Ku laabo",
    ai_insights_header: "Falanqaynta iyo Saadaasha AI",
    ai_insights_desc: "Adeegso garashada mashiinka si aad u hesho xog muhiim ah.",
    total_students_registered: "Wadarta ardayda diiwaangashan waa",
    acceptance_rate: "Heerka aqbalaada",
    get_ai_insights: "Hel Faahfaahinta AI",
    ai_considering_students: "Adiga oo tixgalinaya ardaydan soo socota...",
    ai_analyzing: "AI waxay falanqaynaysaa xogta...",
    overall: "Guud ahaan",
    system_overview: "Xogta Guud ee Nidaamka",
    total_students: "Wadarta Ardayda",
    pending_approval: "Sugaya Aqbalaad",
    active_courses: "Koorsooyinka Firfircoon",
    rejected_by_system: "Laga Diiday Nidaamka",
    recent_notifications: "Fariimihii ugu Dambeeyay",
    choose_app_language: "Dooro Luuqada Codsiga",
    choose_language: "Dooro Luuqad",
    select_language_desc: "Fadlan dooro luuqada aad rabto inuu nidaamku ku shaqeeyo.",
    somali: "Soomaali",
    english: "English",
    amharic: "አማርኛ",
    language_updated: "Luuqada waa la bedelay!",
    confirm_reject: "Ma hubtaa inaad rabto inaad diido codsigan?",
    confirm_delete_course: "Ma hubtaa inaad rabto inaad tirtirto koorsadan?",
    gender_male: "Lab",
    gender_female: "Dhadig",
    reg_paid: "Lacag ah",
    reg_free: "Free ah",
    menu_home: "Hoy",
    menu_about: "Nagu Saabsan",
    menu_service: "Adeegyada",
    menu_contact: "La Xiriir",
    menu_login: "Gali",
    menu_register: "Diiwaangali",
    menu_change_lang: "Baddal Luuqadda"
  },
  en: {
    app_name: "HOGAAN",
    dashboard: "Dashboard",
    pending_list: "Pending Requests",
    register: "Register Student",
    approved_students: "Approved Students",
    manage_courses: "Manage Courses",
    ai_insights: "AI Insights",
    languages: "Languages",
    log_out: "Log Out",
    admin_user: "Admin User",
    main_admin: "Main Admin",
    welcome_system: "Welcome to the modern student registration and management system. Guide your educational future.",
    is_diiwaangali: "Register",
    is_diiwaangali_desc: "If you are a new student wanting to join the school, fill out the registration form here.",
    biloow_hadda: "Start Now",
    gali_koorsooyinka: "Enter Courses",
    gali_koorsooyinka_desc: "If you are an already admitted student, log in to access your courses and lessons here.",
    fura_koorsooyinka: "Open Courses",
    maamulka: "Administration",
    maamulka_desc: "This section is for administrators to verify applications and view school overview statistics.",
    gali_dashboard: "Enter Dashboard",
    all_rights_reserved: "All rights reserved.",
    student_auth: "Student Verification",
    student_auth_desc: "Enter your Email or Phone to access your courses.",
    email_phone: "Email / Phone",
    student_not_found: "Sorry, this student was not found in the system. Please register first.",
    student_pending: "Your application is still pending. Please wait until school approval.",
    student_rejected: "Sorry, your application was rejected.",
    back_home: "Back to Home Page",
    go_back: "Back to Home",
    new_student: "New Student",
    fill_details: "Join the school by completing the details below.",
    full_name: "Full Name",
    email: "Email",
    phone: "Phone",
    gender: "Gender",
    male: "Male",
    female: "Female",
    birth_date: "Date of Birth",
    address: "Address",
    country: "Country",
    registration_type: "Registration Type",
    paid: "Paid",
    free: "Free",
    amount: "Amount",
    currency: "Currency",
    add_student: "Add Student",
    submit_application: "Click here to submit your application",
    success_header: "Congratulations!",
    success_desc: "Your registration has been completed successfully. Your application will be reviewed by the administration.",
    active_approved_students: "Approved Active Students",
    official_student_list: "Official list of students registered in the system.",
    search_placeholder: "Search...",
    contact: "Contact",
    info: "Info",
    address_country: "Address / Country",
    payment: "Payment",
    date: "Date",
    cost: "Cost",
    pending_system_header: "Pending & Approval System",
    pending_system_desc: "Inspect pending student applications waiting for administrative approval below.",
    pending_search_placeholder: "Search name or phone...",
    no_pending_applications: "No pending applications to verify at the moment.",
    approve: "Approve",
    reject: "Reject",
    course_management_header: "Course Management",
    course_management_desc: "Add, modify, or delete courses offered by the system.",
    add_new_course: "Add New Course",
    course_title: "Course Name",
    course_teacher: "Course Teacher",
    course_level: "Course Level",
    course_desc: "Course Description",
    icon: "Icon",
    icon_color: "Icon Color",
    thumbnail: "Thumbnail Image (Optional)",
    current_courses: "Current Active Courses",
    no_courses_found: "No courses found.",
    my_courses: "My Courses",
    welcome_education: "Welcome to your courses",
    teacher: "Teacher",
    level: "Level",
    desc: "Description",
    back: "Back",
    ai_insights_header: "AI Insights & Forecast",
    ai_insights_desc: "Leverage machine learning analysis to uncover core student trends and insights.",
    total_students_registered: "Total registered students is",
    acceptance_rate: "Acceptance rate",
    get_ai_insights: "Get AI Insights",
    ai_considering_students: "Analyzing the following student list...",
    ai_analyzing: "AI is generating database analysis...",
    overall: "Overall",
    system_overview: "School System Dashboard",
    total_students: "Total Students",
    pending_approval: "Pending Approval",
    active_courses: "Active Courses",
    rejected_by_system: "Rejected from System",
    recent_notifications: "Recent Notifications",
    choose_app_language: "Select Application Language",
    choose_language: "Select Language",
    select_language_desc: "Please select the language you want the system to run in.",
    somali: "Somali",
    english: "English",
    amharic: "Amharic",
    language_updated: "Language updated successfully!",
    confirm_reject: "Are you sure you want to reject this request?",
    confirm_delete_course: "Are you sure you want to delete this course?",
    gender_male: "Male",
    gender_female: "Female",
    reg_paid: "Paid",
    reg_free: "Free",
    menu_home: "Home",
    menu_about: "About Us",
    menu_service: "Services",
    menu_contact: "Contact Us",
    menu_login: "Login",
    menu_register: "Register",
    menu_change_lang: "Change Language"
  },
  am: {
    app_name: "ሆጋን (HOGAAN)",
    dashboard: "ዳሽቦርድ",
    pending_list: "የመጠባበቂያ ዝርዝር",
    register: "ተማሪ ምዝገባ",
    approved_students: "የተፈቀዱ ተማሪዎች",
    manage_courses: "ኮርሶች ማስተዳደሪያ",
    ai_insights: "የአይአይ ትንታኔ",
    languages: "ቋንቋዎች",
    log_out: "ውጣ",
    admin_user: "አስተዳዳሪ",
    main_admin: "ዋና አስተዳዳሪ",
    welcome_system: "ወደ ዘመናዊው የተማሪዎች ምዝገባ እና አስተዳደር ስርዓት እንኳን በደህና መጡ። የትምህርት የወደፊት ሁኔታዎን ይምሩ።",
    is_diiwaangali: "ተመዝገብ",
    is_diiwaangali_desc: "አዲስ ተማሪ ከሆኑ እና ትምህርት ቤቱን መቀላቀል ከፈለጉ የምዝገባ ቅጹን እዚህ ይሙሉ::",
    biloow_hadda: "አሁን ጀምር",
    gali_koorsooyinka: "ኮርሶችን ግባ",
    gali_koorsooyinka_desc: "ቀደም ሲል የተመዘገቡ ተማሪ ከሆኑ የእርስዎን ኮርሶች እና ትምህርቶች ለማግኘት እዚህ ይግቡ::",
    fura_koorsooyinka: "ኮርሶችን ክፈት",
    maamulka: "አስተዳደር",
    maamulka_desc: "ይህ ክፍል አስተዳዳሪዎች ማመልከቻዎችን እንዲያረጋግጡ እና አጠቃላይ ውሂብን እንዲያዩ የተዘጋጀ ነው።",
    gali_dashboard: "ዳሽቦርድ ግባ",
    all_rights_reserved: "መብቱ በህግ የተጠበቀ ነው።",
    student_auth: "የተማሪ ማረጋገጫ",
    student_auth_desc: "ኮርሶችዎን ለመክፈት ኢሜይልዎን ወይም ስልክዎን ያስገቡ።",
    email_phone: "ኢሜይል / ስልክ",
    student_not_found: "ይቅርታ፣ ይህ ተማሪ በስርዓቱ ውስጥ አልተገኘም። እባክዎ አስቀድመው ይመዝገቡ።",
    student_pending: "ማመልከቻዎ አሁንም በመጠባበቅ ላይ ነው። እባክዎ በትምህርት ቤቱ እስኪረጋገጥ ድረስ ይጠብቁ።",
    student_rejected: "ይቅርታ፣ ማመልከቻዎ ውድቅ ተደርጓል።",
    back_home: "ወደ መነሻ ገጽ ተመለስ",
    go_back: "ወደ ኋላ ተመለስ",
    new_student: "አዲስ ተማሪ",
    fill_details: "ከታች ያሉትን መረጃዎች በመሙላት ትምህርት ቤቱን ይቀላቀሉ።",
    full_name: "ሙሉ ስም",
    email: "ኢሜይል",
    phone: "ስልክ",
    gender: "ጾታ",
    male: "ወንድ",
    female: "ሴት",
    birth_date: "የትውልድ ቀን",
    address: "አድራሻ",
    country: "ሀገር",
    registration_type: "የምዝገባ ዓይነት",
    paid: "በክፍያ",
    free: "በነጻ",
    amount: "የክፍያ መጠን",
    currency: "የገንዘብ ዓይነት",
    add_student: "ተማሪ ጨምር",
    submit_application: "ማመልከቻዎን ለመላክ እዚህ ይጫኑ",
    success_header: "እንኳን ደስ አለዎት!",
    success_desc: "ምዝገባዎ በተሳካ ሁኔታ ተጠናቋል። ማመልከቻዎ በአስተዳደሩ ይገመገማል።",
    active_approved_students: "የተረጋገጡ ንቁ ተማሪዎች",
    official_student_list: "በስርዓቱ ውስጥ የተመዘገቡ ተማሪዎች ይፋዊ ዝርዝር።",
    search_placeholder: "ፈልግ...",
    contact: "ግንኙነት",
    info: "መረጃ",
    address_country: "አድራሻ / ሀገር",
    payment: "ክፍያ",
    date: "ቀን",
    cost: "ክፍያ",
    pending_system_header: "በመጠባበቅ እና በማጽደቅ ላይ ያሉ ማመልከቻዎች",
    pending_system_desc: "ከዚህ በታች በአስተዳደሩ ይሁንታ በመጠባበቅ ላይ ያሉ የተማሪዎች ማመልከቻዎችን ይመልከቱ።",
    pending_search_placeholder: "በስም ወይም በስልክ ፈልግ...",
    no_pending_applications: "በአሁኑ ጊዜ ለማረጋገጫ በመጠባበቅ ላይ ያለ ማመልከቻ የለም።",
    approve: "አጽድቅ",
    reject: "ውድቅ አድርግ",
    course_management_header: "የኮርሶች አስተዳደር",
    course_management_desc: "በስርዓቱ የሚሰጡ ኮርሶችን ይጨምሩ ወይም ያስተካክሉ።",
    add_new_course: "አዲስ ኮርስ ጨምር",
    course_title: "የኮርስ ስም",
    course_teacher: "የኮርሱ አስተማሪ",
    course_level: "የኮርስ ደረጃ",
    course_desc: "የኮርሱ ማብራሪያ",
    icon: "ምልክት (አይኮን)",
    icon_color: "የምልክት ቀለም",
    thumbnail: "የኮርሱ ምስል (ከተፈለገ)",
    current_courses: "በአሁኑ ጊዜ ያሉ ኮርሶች",
    no_courses_found: "ምንም ኮርስ አልተገኘም።",
    my_courses: "የእኔ ኮርሶች",
    welcome_education: "እንኳን ወደ ትምህርትዎ በደህና መጡ",
    teacher: "አስተማሪ",
    level: "ደረጃ",
    desc: "ማብራሪያ",
    back: "ተመለስ",
    ai_insights_header: "አይአይ (AI) ትንበያዎች እና ትንታኔዎች",
    ai_insights_desc: "ለአስፈላጊ መረጃዎች የማሽን መማሪያ ትንታኔዎችን ይጠቀሙ።",
    total_students_registered: "ጠቅላላ የተመዘገቡ ተማሪዎች ብዛት",
    acceptance_rate: "የመቀበል ፍጥነት",
    get_ai_insights: "የአይአይ ትንታኔን አግኝ",
    ai_considering_students: "የሚከተሉትን ተማሪዎች መረጃ ከግምት ውስጥ በማስገባት...",
    ai_analyzing: "አይአይ መረጃዎችን በመተንተን ላይ ነው...",
    overall: "አጠቃላይ",
    system_overview: "የስርዓቱ አጠቃላይ እይታ",
    total_students: "ጠቅላላ ተማሪዎች",
    pending_approval: "ይሁንታ በመጠባበቅ ላይ",
    active_courses: "ንቁ ኮርሶች",
    rejected_by_system: "ውድቅ የተደረጉ",
    recent_notifications: "የቅርብ ጊዜ ማሳወቂያዎች",
    choose_app_language: "የመተግበሪያውን ቋንቋ ይምረጡ",
    choose_language: "ቋንቋ ይምረጡ",
    select_language_desc: "እባክዎ መተግበሪያው እንዲሰራበት የሚፈልጉትን ቋንቋ ይምረጡ።",
    somali: "ሶማሊኛ",
    english: "እንግሊዝኛ",
    amharic: "አማርኛ",
    language_updated: "ቋንቋው በተሳካ ሁኔታ ተቀይሯል!",
    confirm_reject: "ይህን ማመልከቻ ውድቅ ለማድረግ እርግጠኛ ነዎት?",
    confirm_delete_course: "ይህን ኮርስ ለመሰረዝ እርግጠኛ ነዎት?",
    gender_male: "ወንድ",
    gender_female: "ሴት",
    reg_paid: "በክፍያ",
    reg_free: "በነጻ",
    menu_home: "መነሻ",
    menu_about: "ስለ እኛ",
    menu_service: "አገልግሎቶች",
    menu_contact: "ያግኙን",
    menu_login: "ግባ",
    menu_register: "ተመዝገብ",
    menu_change_lang: "ቋንቋ ቀይር"
  }
};

interface LanguageContextProps {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageType>(() => {
    const saved = localStorage.getItem('hogaan_language');
    // Default is Somali ('so')
    return (saved === 'so' || saved === 'en' || saved === 'am') ? saved as LanguageType : 'so';
  });

  const setLanguage = (lang: LanguageType) => {
    setLanguageState(lang);
    localStorage.setItem('hogaan_language', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['so']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
